# Config file for travis-ci.org

language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
install: sh travis.sh
script: mv lib/plugins/canonicalchinese/phpunit.xml _test/ && cd _test && phpunit --stderr --group plugin_canonicalchinese --coverage-clover=coverage.xml
after_success: bash <(curl -s https://codecov.io/bash)

